import Head from 'next/head';
import { Button } from 'reactstrap';
import { DefaultLayout } from '@/components/layouts';

export interface HomePageProps {}

const Home = (props: HomePageProps) => {
    console.log(1234);
    return (
        <div>
            <Head>
                <title>Love9x Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Button>Ahihi 123</Button>
        </div>
    );
};

Home.Layout = DefaultLayout;

export default Home;
